### ISSUE TITLE
"Injector has already been destroyed" error when ng adding latest RC

### ISSUE THREAD

**Issue by valadzhov** [IgniteUI/igniteui-cli#1011]
### Description  
There are errors in the console when you run the tests for a project with ng added igniteui-angular.

### Steps to reproduce  

1. Create a new Angular project with `ng new`
2. Add the latest IgniteUI for Angular with `ng add igniteui-angular@13.1.0-rc.1`
3. Add all components with the `ng g` command `(ng g @igniteui/angular-schematics:c grid newGrid
)`
4. Run the npm script test inside the project.
### Result  
There are errors in the console related to the injector already having been destroyed.

### Expected result  
There shouldn't be any errors when you run the tests.

### Attachments  
![image](https://user-images.githubusercontent.com/9549439/155987383-5ad3cb0c-cad0-4d25-b6d8-55191be00887.png)

**Comment by Lipata** [comment]
Already fixed
