### ISSUE TITLE
WC project with grid does not add ignite-ui npm packages

### ISSUE THREAD

**Issue by wnvko** [IgniteUI/igniteui-cli#1121]
### Description  
ignite-ui packages are missing from the project.

- Ignite UI CLI version: 11.0.3
- Framework: Web Components

### Steps to reproduce  

1. Create new WC project with cli and add a grid component

### Result  
Application cannot build and run as ignite-ui packages are missing.

### Expected result  
Application should have all necessary packages and should build, run, lint and test with no errors.

**Comment by valadzhov** [comment]
Closing the issue, it's duplicate of https://github.com/IgniteUI/igniteui-cli/issues/1109
