### ISSUE TITLE
Unify templates in different frameworks

### ISSUE THREAD

**Issue by dafo** [IgniteUI/igniteui-cli#115]
There are differences between the templates in the different frameworks. Mostly in the list of choices but also in the names of the templates:
•	grid-custom (jQuery) is missing GroupBy choice
•	grid-editing (React) doesn’t have Updating by default but as a choice. Choices are missing Paging.
•	grid-export: in jQuery choices are Sorting, Paging and Filtering. In React – Summaries and Hiding
•	hierarchical-grid-custom (React) is missing Paging and Summaries choices
•	hierarchical-grid-editing (React) I missing Paging. Updating is listed as a choice no matter that it is enabled by default
•	hierarchical-grid-exporting: in jQuery choices are Sorting, Paging and Filtering. In React – Summaries and Hiding
•	tree-grid-basic in Angular and jQuery should be tree-grid
•	tree-grid-custom in jQuery and Angular has Filtering listed two times
•	tree-grid-updating in jQuery and Angular is missing Updating. In React Updating is a choice. It should be set by default for all frameworks.
•	tree-grid-export: in jQuery Summaries option is missing. In React Filtering option is missing.
•	tree-grid-file-explorer in jQuery is placed under the custom-templates folder and not under tree-grid. Also it is missing the choices (Sorting)
•	In Angular and jQuery Combo and Editors are in group “Data Entry”. In React they are in group “Editors”

**Comment by IvayloG** [comment]
•	No Summaries feature exists in tree-grid.
•	Renaming $(Gridfeatures) to $(treeGridFeatures) for jQuery/React tree-grid templates.
