### ISSUE TITLE
Can't use charts when using 12.0.6-beta.0 CLI

### ISSUE THREAD

**Issue by mystoev** [IgniteUI/igniteui-cli#1154]
### Description  
Going through the installer, and trying to have any of the charts' templates (for example, doughnut chart), the project fails to install the libraries. Even when explicitly installing the charts, they don't seem to render.

- Ignite UI CLI version: 12.0.6-beta.0
- Framework: React

### Steps to reproduce  

1. Run the CLI, and use any project name
2. Choose React with TypeScript
3. Use "Default top navigation"
4. Add Doughnut Chart and give it some name
5. "Complete & Run" and use default port

### Result  
Error saying: 
```Cannot find package 'vite' imported from ...vite.config.ts ...```

No **node_modules** folder installed. Trying to ```npm i``` fails with:
```
npm ERR! Found: igniteui-react-core@18.2.2-beta.0
npm ERR! node_modules/igniteui-react-core
npm ERR!   igniteui-react-core@"18.2.2-beta.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer igniteui-react-core@"16.15.1" from igniteui-react-charts@16.15.1
npm ERR! node_modules/igniteui-react-charts
npm ERR!   igniteui-react-charts@"~16.15.0" from the root project
```
Using ```npm i --force``` installs the libraries, but when the app is started, the chart is not rendered, failing with multiple errors in the console

### Expected result  
Libraries should be installed, and when the project is started, the chart should be visualized.

### Attachments  
Part of the errors:
<img width="651" alt="Screenshot 2023-10-03 at 11 27 54" src="https://github.com/IgniteUI/igniteui-cli/assets/2042518/9b25eda7-ae65-4406-8978-c97e8c19a16c">

**Comment by onlyexeption** [comment]
Please use igniteui-cli version 12.1.0-beta.0 globally. The issue should be resolved when using that version.
