### ISSUE TITLE
Warning in terminal when running React project

### ISSUE THREAD

**Issue by mystoev** [IgniteUI/igniteui-cli#1156]
### Description  
When you bootstrap a project with React TS and run the application, there is a warning message from vite in the terminal/command prompt.

- Ignite UI CLI version: **12.1.0-beta.0**
- Framework: **React**
- Project type: **igr-ts**

### Steps to reproduce  

1. Run the CLI and give any project name
2. Framework: **React**
3. Project type: **Ignite UI for React TS**
4. Template: **Default top navigation**
5. Action: **Complete & Run**
6. Port: **default**
7. Run the app from the terminal/command prompt
8. Make sure the app is rendered in the browser

### Result  
A warning from vite is shown in the terminal/command prompt - see attachments

### Expected result  
No such warning

### Attachments  
<img width="1785" alt="Screenshot 2023-10-05 at 10 55 29" src="https://github.com/IgniteUI/igniteui-cli/assets/2042518/157350a9-d59a-40d5-bf73-23a6403c55b1">

**Comment by onlyexeption** [comment]
Resolved in 12.1.0-beta.1
