### ISSUE TITLE
No need for react-router-dom in base and empty project templates

### ISSUE THREAD

**Issue by mystoev** [IgniteUI/igniteui-cli#1157]
### Description  
When you use ```Base project``` or ```Empty project``` template the ```react-router-dom``` is not used, hence not necessary.

- Ignite UI CLI version: 12.1.0-beta.1
- Framework: React
- Project type: igr-ts

### Steps to reproduce  

1. Start the CLI
2. Choose React with TS
3. Use the ```Empty project``` or ```Base project``` template
4. Finish the bootstrapping of the project

### Result  
```react-router-dom``` is installed, but not used.

### Expected result  
```react-router-dom``` should not be included in package.json and not installed.

**Comment by onlyexeption** [comment]
Closing this issue as React Router now provides the default routing implementation for both `Base` and `Empty` templates.
