### ISSUE TITLE
bindToComponentInputs, withComponentInputBinding & provideHttpClient should be included only for projects that need them

### ISSUE THREAD

**Issue by jackofdiamond5** [IgniteUI/igniteui-cli#1210]
### Description  
Currently we've included the `bindToComponentInputs`, `withComponentInputBinding` & `provideHttpClient` in the base template for all of our projects. Instead, we should be adding them only if the project has route parameters and is explicitly using the `HttpClient` somewhere in the code.

We may also want to consider reworking the error routing for the projects.

- Ignite UI CLI version: 13.1.6
- Framework: Angular
- Project type: igx-ts

### Expected result  
 `bindToComponentInputs`, `withComponentInputBinding` & `provideHttpClient` should be included only for apps that need them

**Comment by dafo** [comment]
Until this is fixed, AB's "CRM App" sample application will be throwing error in Angular Standalone.
