### ISSUE TITLE
should have .gitignore for new ng projects

### ISSUE THREAD

**Issue by jVanZwieten** [IgniteUI/igniteui-cli#122]
The Angular cli (ng new test-project) includes a .gitignore to new projects by default. This is extremely useful and, since this is the precedent set by the ng team, I recommend we include it in new ng projects created by igniteui-cli.

**Comment by kdinev** [comment]
Adding `jquery` and `react` since the `.gitignore` should be added to all.

**Comment by damyanpetev** [comment]
@kdinev Should we also `git init + commit` when we create project structure?

**Comment by kdinev** [comment]
@damyanpetev What do other CLIs do?

**Comment by damyanpetev** [comment]
@kdinev Seems like most do with either a command flag or config option to skip/disable, just create react app seems to drop a `.gitignore` without an option to actually init a repo.

**Comment by kdinev** [comment]
Then we should also add a flag.

**Comment by Lipata** [comment]
https://github.com/IgniteUI/igniteui-cli/issues/169 I've created separate issue git init and git commit flags

**Comment by bazal4o** [comment]
I'm closing the issue, because the leftovers are moved to issue #169
