### ISSUE TITLE
CLI should generate unique selector for each newly added component

### ISSUE THREAD

**Issue by bkulov** [IgniteUI/igniteui-cli#129]
I'm using the CLI to generate components in Angular project (not Angular wrappers). Currently all newly generated components have hardcoded selector 'app-home'.

I think the CLI should generate unique selector corresponding to component name for each new component.

**Comment by wnvko** [comment]
We are using angular build in routing to show each component. Therefore we actually do not need selector.  This is why I will remove all the selectors from all templates.

**Comment by wnvko** [comment]
After discussing this with @rkaraivanov we decided to leave the selectors for each template. Now each template will have a selector with its dashed name.
