### ISSUE TITLE
Incorrect Module Imports in app.config.ts

### ISSUE THREAD

**Issue by georgianastasov** [IgniteUI/igniteui-cli#1319]
### Description  
When generating an Angular project using the latest version of igniteui-cli, the app.config.ts file contains incorrect import statements. The imports for Ignite UI for Angular components are incorrectly generated with a placeholder (`<%=igxPackage%>`) instead of the actual package name (`igniteui-angular`). This results in a TypeScript error during application bundle generation.

    Ignite UI CLI version: 14.0.1
    Framework: Angular
    Project type: igx-ts

### Steps to reproduce  
<img width="660" alt="c" src="https://github.com/user-attachments/assets/2dc9b1c8-c34f-4bc0-b478-94207f546bd8">

### Result  
The project fails to build due to a TypeScript error caused by incorrect imports in the `app.config.ts` file. The import statement:
```
import {
    IgxNavigationDrawerModule,
    IgxNavbarModule,
    IgxLayoutModule,
    IgxRippleModule,
} from '<%=igxPackage%>';
```

### Expected result  
The app.config.ts file should contain valid import statements, importing from `igniteui-angular`:
```
import {
    IgxNavigationDrawerModule,
    IgxNavbarModule,
    IgxLayoutModule,
    IgxRippleModule,
} from 'igniteui-angular';
```

### Attachments  
[Test-App-Error.zip](https://github.com/user-attachments/files/17042672/Test-App-Error.zip)

**Comment by Lipata** [comment]
@georgianastasov fixed is released in [igniteui-cli@14.0.2](https://github.com/IgniteUI/igniteui-cli/releases/tag/v14.0.2)
