### ISSUE TITLE
IgniteUI for Angular startup project still referencing js-blocks

### ISSUE THREAD

**Issue by jVanZwieten** [IgniteUI/igniteui-cli#136]
### Description
New Angular projects started from IgniteUI CLI still references the deprecated igniteui-js-blocks. This should be updated to reference the new igniteui-angular

### Steps to Reproduce
1. ig new new-project --framework=angular
2. check /package.json

### Result
`"igniteui-js-blocks": "^5.0.1",`

### Expected
`"igniteui-angular": "^5.1.0",`

**Comment by damyanpetev** [comment]
@jVanZwieten Work on the package change is already in progress, we were just waiting on a few updates in the product, that seem to be done, so the update should be coming soon(tm).
