### ISSUE TITLE
Add a command to generate an empty custom template for extensibility

### ISSUE THREAD

**Issue by kdinev** [IgniteUI/igniteui-cli#146]
The CLI should expose a command which generates an empty custom template for a framework, which can then be modified to become a full custom template.

The command should allow for framework selection: `react`, `ng`, `jquery`.

**Comment by bazal4o** [comment]
@sbozalieva - could you help us with the name of the command. We think for something like "generate", but as it sounds more generic it's not self explaining it's generating empty template. Any thoughts? 
What type of arguments should we provide?

**Comment by sbozalieva** [comment]
@bazal4o As discussed I also stand by generate and adding it globally. 

- generate

And even if it might be a bit long,  adding custom/empty, which is what makes it different from a template in general.

`ig generate custom-template `

- install

 Since you install it in the cli itself.

`ig install custom-template`

**Comment by sbozalieva** [comment]
`ig generate`: Generates custom template in the working folder and the global CLI config file.

- `generate`: alias `g`. Default to the only sub-command so far`template`.

`ig generate template [name]`

- `template`:  alias `-tm`

- `name`: Creates a folder and fills in the id/name. It is optional. Default value is <custom-template>.  _We already have that argument. Not sure if it will interfere or not._

`--framework=<framework>:` alias `-f`.  Selects framework. Default is "jquery".

`--type=<type>`: alias `-t`. Selects the type of the project (framework dependent). Default is "jquery-js".

`--skip-config`. Skips registering generated path in the global CLI config. Creates the template in the working folder only.

**Comment by bazal4o** [comment]
@kdinev @SlavUI  Do you agree with the proposed approach ?

**Comment by wnvko** [comment]
Help looks like this now
Commands:
  template [name] [framework] [type]        Generates custom template
  [skipconfig]                                                      [aliases: t]

Options:
  --version, -v     Show current Ignite UI CLI version                 [boolean]
  --help, -h        Show help                                          [boolean]
  --name, -n        Template name.         [string] [default: "custom-template"]
  --framework, -f   Framework name.                 [string] [default: "jquery"]
  --type, -t        Framework type.                     [string] [default: "js"]
  --skip-config, -s  Skips adding to the config.
                                                      [boolean] [default: false]
