### ISSUE TITLE
Add git options to ig new command

### ISSUE THREAD

**Issue by Lipata** [IgniteUI/igniteui-cli#169]
Add options for git init and git commit commands. We should decide that when we create a new project with ig new command:
 - to directly init and commit it, without any defined flags (like in angular-cli), and in the same time have a flags that allow to skip them. In angular-cli the [flags are](https://github.com/angular/angular-cli/wiki/new) --skip-git and --skip-commit.
 - to define two flags that will allow git init and git commit.

We should decide how those flags (and their alias-es) will be named, if commit flag will do both, and if the commit message could be modified.

**Comment by kdinev** [comment]
Related #122

**Comment by Lipata** [comment]
@sbozalieva, @kdinev, we can also have configuration options instead command options. It's preferable that the commit happens automatically with the creation of the project - so either use --skip flags or configuration. The latter will allow a custom commit message.

**Comment by sbozalieva** [comment]
@Lipata I agree. Lets go the angular way.:)

**Comment by jVanZwieten** [comment]
Aught to include a .gitignore like the ng cli does.

**Comment by damyanpetev** [comment]
@jVanZwieten Yeah, project templates already have [`.gitignore` files](#122) but we landed on an old npm pack bug that renamed them when publishing, so they didn't end up in the final package properly.
Working on it, about to test an update (https://github.com/IgniteUI/igniteui-cli/pull/205) for 1.2.1 soon
