### ISSUE TITLE
Provide more detailed `dependencies` format for Ignite UI for Angular project

### ISSUE THREAD

**Issue by bazal4o** [IgniteUI/igniteui-cli#200]

**Comment by damyanpetev** [comment]
So far the plan is to break down the current style of [module dependency listing](https://github.com/IgniteUI/igniteui-cli/blob/master/templates/angular/igx-ts/custom-templates/awesome-grid/index.ts#L13) into more descriptive objects, kind of like igniteui-angular-samples. Those still implicitly modify the main `app.module.ts` but won't be restricted to just modules from one package import like:
```ts
dependencies = [
  { import: "IgxAvatarModule", from: "igniteui-angular/main" },
  { declare: "SomeComponent", from ".."},
  { provide: "Service", from ".."}
];
```
- An **import** entry will both import the module from the package and add it to the `imports` metadata of the main [`NgModule`](https://angular.io/api/core/NgModule).
  This can also be applied to the Grid module like: 
  ```ts
  { import: "IgxGridModule", from: "igniteui-angular/grid", root: true /* OR */ call: "forRoot" }
  ```
  Could also allow multiple identifiers per import:
  ```ts
  { import: "IgxIconModule, IgxAvatarModule, IgxBadgeModule", //...
  ```
- An **declare** entry will both import the component and add it to the ` declarations` metadata of the main `NgModule`. The from location will likely have to include some path placeholders. Might not be a must have, intended for mostly declaring additional components, as the one per template is added anyway.

- An **provide** entry will both import the identifier and add it to the ` providers` metadata of the main `NgModule`. Mostly intended for templates to be able to provide services so it doesn't cover much more complicated providers. We can always extend with `useClass`/`useValue` in the future I guess.

This will allow for templates to both load modules from separate barrels, bring in ones from Angular (e.g. Forms Module) or other packages.

Am I missing major cases? Would love some feedback.
//CC @kdinev @rkaraivanov @tiliev

**Comment by tiliev** [comment]
Hello @damyanpetev,
I don't think you are missing any major cases. We find these types of configurations with the hard-coded types a little bit unreliable if a module/component name change occurs in future. That's why we are currently developing a  way of providing the configuration like this:
![capture](https://user-images.githubusercontent.com/6439482/37145915-e283ca20-22ca-11e8-8235-dbe348fdfa24.PNG)
We'd like to have type checking. But if you have a proper testing, the hard-coded strings won't be an issue.

**Comment by damyanpetev** [comment]
@tiliev Thanks for the feedback.
Unfortunately, out template descriptions are somewhat detached from any source and should work even with simple JSON files users can provide to extend the CLI. We can't quite guarantee access to packages and typescript, so the strings will have to do for now.
