### ISSUE TITLE
Step by Step mode: update default naming as the user adds more templates.

### ISSUE THREAD

**Issue by sbozalieva** [IgniteUI/igniteui-cli#215]
### Description  

Default names helpful until an user wants to add more projects to the same folder or more components of the same kind to the same project.

### Result

> ? Enter a name for your project: app
....
Complete & Run!

> ? Enter a name for your project: app
Folder "app" already exists!

### Expected Result

Adding 1, 2 etc to the default naming.

> ? Enter a name for your project: app
....
Complete & Run!

> ? Enter a name for your project: app1
....
Complete & Run!

**Comment by bazal4o** [comment]
Not really sure if we can check all the combinations, but we can try to include some basic check and add number at the end.
