### ISSUE TITLE
Step by Step mode: Update default naming

### ISSUE THREAD

**Issue by sbozalieva** [IgniteUI/igniteui-cli#216]
- [x] Change default name for project

### Description  
Change default project name to to Ig Project

> ? Enter a name for your project: (app) 

### Expected Result

> ? Enter a name for your project: (IG Project)

- [ ] Update ids with "names" of the templates:

###  Result

> ? Select features for the **igGrid**: Sorting

### Expected Result

> ? Select features for the **Grid**: Sorting

**Comment by IvayloG** [comment]
- [x] Default name is changed to "IG Project" in the following PR "Increment default names suggested, based on existing folders #330"

- [ ] It seems more valuable to leave the component names with the corresponding prefixes like igGrid and igxGrid etc. As they give more information regarding the component name in different frameworks.
