### ISSUE TITLE
Add Login View

### ISSUE THREAD

**Issue by bazal4o** [IgniteUI/igniteui-cli#336]
It should be under add view. We can discuss possibility - when added to create login button in the top right corner. 

We have an option to have an extra configuration which controls weather or not to add the button, or list it in the navigation menu

**Comment by dafo** [comment]
![getting-started](https://user-images.githubusercontent.com/2778393/44021744-40000926-9eee-11e8-95ca-9223b93d2096.png)
Login view
![getting-started2](https://user-images.githubusercontent.com/2778393/44021748-41cc1f06-9eee-11e8-8352-ec0c64bf78c7.png)
Registration view (incase we need such)
