### ISSUE TITLE
Currently there's no difference between add view and add component

### ISSUE THREAD

**Issue by kdinev** [IgniteUI/igniteui-cli#366]
### Description  
The current version of the CLI does one and the same thing when `view` and `component` are selected to be added. If I do an `ng generate component` then I will get a component, but no routing for it. When adding a view from the `igniteui-cli` I should be getting routing update, but not when adding a component.

- Ignite UI CLI version: 2.1.0
- Framework: Angular
- Project type: igx-ts

**Comment by bazal4o** [comment]
I've created another issue as we discussed to have the ability to add a view without registering it to the navigation. #368 

The difference between add template and add view is in the semantic. The expectation is the view is more complex (most of the cases with more than one component in it)  while the template itself contains only the component with the predefined configuration. 

I suggest we close this issue and work on the linked one.
