### ISSUE TITLE
'ig test' fails on a new project unless --skipAnalytics is set

### ISSUE THREAD

**Issue by vanguard737** [IgniteUI/igniteui-cli#373]
### Description  
After you create a new igx-ts/Angular project, 'ig test' throws UnhandledPromiseRejectionWarning and fails.  Workaround is to specify --skipAnalytics.

- Ignite UI CLI version: 2.1.1
- Framework: Angular
- Project type: igx-ts

### Steps to reproduce  

1. Create new project:
ig new --name foo --framework angular --type igx-ts --theme Default

2. Build the project and run 'ig test':
cd foo
ig build
ig test

3. Observe that you get the exception shown in '### Result' below.

4.  Run 'ig test --skipAnalytics' and observe that tests succeed as expected. 

5.  Additionally, FWIW, note that setting disableAnalytics to true doesn't help.  Try this:
ig config set disableAnalytics true -g
ig test
...and observe that you still get UnhandledPromiseRejectionWarning.

### Result  
What is the actual result after following the steps to reproduce?
Exception when running 'ig test' without --skipAnalytics:
(node:12340) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'framework' of undefined
    at Object.<anonymous> (C:\Users\cjbro\Dropbox\workspace\tmp\foo\node_modules\igniteui-cli\lib\commands\test.js:45:45)
    at Generator.next (<anonymous>)
    at C:\Users\cjbro\Dropbox\workspace\tmp\foo\node_modules\igniteui-cli\lib\commands\test.js:7:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\cjbro\Dropbox\workspace\tmp\foo\node_modules\igniteui-cli\lib\commands\test.js:3:12)
    at Object.test (C:\Users\cjbro\Dropbox\workspace\tmp\foo\node_modules\igniteui-cli\lib\commands\test.js:34:16)
    at Object.<anonymous> (C:\Users\cjbro\Dropbox\workspace\tmp\foo\node_modules\igniteui-cli\lib\commands\test.js:30:21)
    at Generator.next (<anonymous>)
    at C:\Users\cjbro\Dropbox\workspace\tmp\foo\node_modules\igniteui-cli\lib\commands\test.js:7:71
    at new Promise (<anonymous>)
(node:12340) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled
with .catch(). (rejection id: 1)
(node:12340) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

### Expected result  
What is the expected result after following the steps to reproduce?
Tests should succeed with 'ig test' as they do with 'ig test --skipAnalytics'.  Console output from the latter, if that helps:
ig test --skipAnalytics
> foo@0.0.0 test C:\Users\cjbro\Dropbox\workspace\tmp\foo
> ng test

 10% building modules 1/1 modules 0 active(node:5352) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
14 10 2018 05:06:22.679:WARN [karma]: No captured browser, open http://localhost:9876/
14 10 2018 05:06:22.687:WARN [karma]: Port 9876 in use
14 10 2018 05:06:22.689:INFO [karma]: Karma v1.7.1 server started at http://0.0.0.0:9877/
14 10 2018 05:06:22.689:INFO [launcher]: Launching browser Chrome with unlimited concurrency
14 10 2018 05:06:22.695:INFO [launcher]: Starting browser Chrome                                                                                                              14 10 2018 05:06:29.343:WARN [karma]: No captured browser, open http://localhost:9877/
14 10 2018 05:06:29.843:INFO [Chrome 69.0.3497 (Windows 10.0.0)]: Connected on socket daBIUQ1-Qf6poijTAAAA with id 16253597
Chrome 69.0.3497 (Windows 10.0.0): Executed 2 of 2 SUCCESS (0.299 secs / 0.254 secs)

### Attachments  
Attach a sample if available, and screenshots, if applicable.

**Comment by damyanpetev** [comment]
Thanks for reporting!
Fix is available with [v1.3.5](https://github.com/IgniteUI/igniteui-cli/releases/tag/v1.3.5) and [v2.1.2](https://github.com/IgniteUI/igniteui-cli/releases/tag/v2.1.2)
