### ISSUE TITLE
Add option for generating empty CLI project including welcome product page

### ISSUE THREAD

**Issue by StefanIvanov** [IgniteUI/igniteui-cli#401]
### Description  
Provide an option to create an empty Ignite UI for Angular project with product info via the CLI i.e. as if ng new *** --style=scss was triggered

### Expected result  
New empty project with product info

**Comment by damyanpetev** [comment]
@StefanIvanov care to elaborate?
`ig new newIgniteUIAngular --framework=angular --type=igx-ts` will already generate **only files** for the project structure without installing anything just yet. [Wiki](https://github.com/IgniteUI/igniteui-cli/wiki/new). 
Actual install happens once per project on `ig start`/`ig build` as needed. [Wiki](https://github.com/IgniteUI/igniteui-cli/wiki/build).

Is there anything specific required for the code generation to work after that?

**Comment by StefanIvanov** [comment]
I should have elaborated initially :) I imagine a third option here that says: Indigo.Design Generated
<img width="315" alt="screen shot 2018-11-12 at 2 43 42 pm" src="https://user-images.githubusercontent.com/1702064/48348247-77d29e80-e689-11e8-9ff6-69d65fb50420.png">

**Comment by damyanpetev** [comment]
@StefanIvanov Or here, depending on compatibility:
![image](https://user-images.githubusercontent.com/3198469/48356086-254fad00-e69e-11e8-81be-dc763fd4a792.png)

Any app layout details? Ignite UI for Angular setup? Anything else?

**Comment by StefanIvanov** [comment]
It could be at the step @damyanpetev mentions as well if say some day more frameworks are added and supported by code gen. The generated project should be empty without any extra added stuff as code gen adds whatever is needed based on the screen designs.

**Comment by StefanIvanov** [comment]
Also we could have a command that goes like ig new NameIT —codegen

**Comment by StefanIvanov** [comment]
@SlavUI  can we add this to the current sprint together with the other updates that are planned for the CLI?
