### ISSUE TITLE
Adding a scenario of "Login View" fails to be built with an error "Module not found"

### ISSUE THREAD

**Issue by norikois** [IgniteUI/igniteui-cli#430]
### Description  
Adding a scenario of "Login View" fails to run

- Ignite UI CLI version:  3.2.1
- Framework: Angular
- Project type: IgniteUI for Angular

### Steps to reproduce  

1. "ig" and create a project step by step.
2. At "Choose an action", choose "Add scenario".
3. At "Choose custom view", choose "Login View".
4. "Complete & Run".

Here is what is specified in the step by step mode:

Starting Step by step mode.
For available commands, stop this execution and use --help.

? Enter a name for your project: my-app2
  Framework: Angular
  Project type: Ignite UI for Angular
? Choose project template: Default side navigation
? Choose the theme for the project: Default
  Generating project structure.
√ Project structure generated.
√ Git Initialized and Project 'my-app2' Committed

? Choose an action: Add scenario
? Choose custom view: Login view
? Name your view: myView1
√ View 'myView1' added.

? Choose an action: Complete & Run
? Choose app host port: 4200

### Result  
ERROR in ./src/app/myview1/myview1.component.ts
Module not found: Error: Can't resolve './login-view.component.html' in 'my-app2\src\app\myview1'
ERROR in ./src/app/myview1/myview1.component.ts
Module not found: Error: Can't resolve './login-view.component.scss' in 'my-app2\src\app\myview1'
i ｢wdm｣: Failed to compile.

### Expected result  
The application should be launched without error.

### Attachments  
Attach a sample if available, and screenshots, if applicable.  
Attached a project which is created by the above step.
[my-app2.zip](https://github.com/IgniteUI/igniteui-cli/files/2707914/my-app2.zip)

**Comment by Lipata** [comment]
This is resolved
