### ISSUE TITLE
Angular httpinterceptor(jwt token header) not working after importing IgxTreeGridModule in lazy loaded module

### ISSUE THREAD

**Issue by badre429** [IgniteUI/igniteui-cli#484]
### Description  
Angular httpinterceptor(jwt token header) not working after importing IgxTreeGridModule in lazy loaded module

- Ignite UI CLI version: no
- Framework: Angular
- Project type: igx-ts

### Steps to reproduce  

1. create lazy loaded module 
2. import  IgxTreeGridModule in the module 

### Result  
in the app module httpinterceptor is working 
![image](https://user-images.githubusercontent.com/5818051/54189001-2b6d6300-44b1-11e9-849b-fa08c581166e.png)
in the lazy loaded module the unterceptor stop 

![image](https://user-images.githubusercontent.com/5818051/54189175-8a32dc80-44b1-11e9-8aa2-4a70612f190f.png)

### Expected result  
if we remove IgxTreeGridModule from import list in the lazy loaded it works 
![image](https://user-images.githubusercontent.com/5818051/54189504-3e346780-44b2-11e9-9bd7-68224cb4fc6f.png)

### code for this issue
https://github.com/badre429/igx-jwt-error

[or live on stackblitz](https://stackblitz.com/github/badre429/igx-jwt-error)

**Comment by badre429** [comment]
sorry i moved this to igniteui-angular  https://github.com/IgniteUI/igniteui-angular/issues/4285

**Comment by zdrawku** [comment]
Github now provides a way to transfer issues from one reposit to another, you can check it [here](https://help.github.com/en/articles/transferring-an-issue-to-another-repository).

Screenshot:
![image](https://user-images.githubusercontent.com/11193764/54192009-b5bcc380-44bf-11e9-9e10-706c55fecb47.png)
