### ISSUE TITLE
Inquirer's prompt is blocking the terminal

### ISSUE THREAD

**Issue by dafo** [IgniteUI/igniteui-cli#519]
### Description  
When initializing the step by step mode, the terminal is blocked after you are prompted to choose a project template.

- Ignite UI CLI version: 4.1.x
- Framework: Angular|React|jQuery
- Project type: ig-ts|igx-ts

### Steps to reproduce  

1. Execute `ig`
2. Enter a name for your new project
3. Try to select a project template

### Result  
The terminal is blocked. You cannot select a template and you cannot even close the terminal.

### Expected result  
A project template is selected

**Comment by damyanpetev** [comment]
This seems to be due to the latest 6.4.0 release of inquirer: https://github.com/SBoudrias/Inquirer.js/issues/811

Will be restricting the version we use for now.
