### ISSUE TITLE
Update CRM Grid template toolbar

### ISSUE THREAD

**Issue by damyanpetev** [IgniteUI/igniteui-cli#535]
### Description  
Describe the issue.

- Ignite UI CLI version: 4.2.x
- Framework: Angular
- Project type: igx-ts

### Steps to reproduce  

1. Create an Ignite UI for Angular project
2. Add CRM Grid from scenarios
3. Observe the toolbar styling

### Result  
The padding of the buttons is off and it doesn't match the official demo:
![image](https://user-images.githubusercontent.com/3198469/61213752-9d2f1500-a70e-11e9-8e83-b15ed2ebd1dc.png)

### Expected result  
Should look like the official demo at https://www.infragistics.com/products/ignite-ui-angular#angular-grid:
![image](https://user-images.githubusercontent.com/3198469/61213773-ae782180-a70e-11e9-80a0-7566f8198eb1.png)

**Comment by dafo** [comment]
This will be fixed by #628
