### ISSUE TITLE
Fix failing tests in the generated projects

### ISSUE THREAD

**Issue by Lipata** [IgniteUI/igniteui-cli#545]
Fix lint errors

Ignite UI CLI 4.2.3
Framework: Angular|React|jQuery
Project type: ig-ts|igx-ts
Steps to reproduce
Create a project with all the available components and views.
Run npm run test.
Result
There are several failing tests.

Expected result
No failing tests

**Comment by ViktorSlavov** [comment]
DV Tests will be fixed in #561
