### ISSUE TITLE
ng build --prod throws Property 'classFromType' is private and only accessible within class 'GridComponent'.

### ISSUE THREAD

**Issue by zdrawku** [IgniteUI/igniteui-cli#554]
### Description  
Error is thrown on `ng build --prod`

- Ignite UI CLI version: 4.2.4
- Framework: Angular
- Project type: igx-ts

### Steps to reproduce  

1.  Execute the following configuration. Create a Grid with Batch Editing
![image](https://user-images.githubusercontent.com/11193764/64682566-5d747780-d48a-11e9-8a71-96ab3ddb6d90.png)
2. Run `ng build --prod`

### Result  
![image](https://user-images.githubusercontent.com/11193764/64682604-6d8c5700-d48a-11e9-9ab7-ae9e1e28e89b.png)

**Comment by ViktorSlavov** [comment]
This was fixed in [this PR](https://github.com/IgniteUI/igniteui-cli/commit/820d3f4379d3dbb55088a85b198cfd0c55a02dbd#diff-50f1e7eb9e94f9b4984f990776e42c99R53). Closing.
