### ISSUE TITLE
[NG schematics] - ng-add and component schematics do not account for virtual file system 

### ISSUE THREAD

**Issue by ViktorSlavov** [IgniteUI/igniteui-cli#576]
### Description  
Currently, the check whether a file (folder) exists is done in `Util` and does not account for the virtual tree when used in the context of the schematics. This leads to calling `ng-add` and `component` not properly prompting a default name and not properly erroring when the name already exist.

- Ignite UI CLI version: 5.0.0
- Framework: Angular|React|jQuery
- Project type: ig-ts|igx-ts

### Steps to reproduce  

1. Run `ng new --collection=@igniteui/angular-schematics`
2. Project Type => Default Side Navigation
3. Add Component => Grid => Grid (do not change the name)
4. Repeat Step 3 several times
5. Complete & Run

### Result  
The prompt does not change the default name to `Grid [increment]`.
In the end, only on Grid component (grid) is created (though routes are added for each instance)

### Expected result  
The prompt changes the default name to `Grid [increment]`.
Separate grid components with the proper names are created in the end.

**Comment by damyanpetev** [comment]
Yeap, fairly certain the increment is a Util method that doesn't handle the virtual fs. Actually nothing in Util does, though there are general access methods that can be replaced with the fs.
Just keep in mind those are used everywhere and I seem to remember some of those were intentionally used without fs even for schematics.
