### ISSUE TITLE
[Templates] Angular 9 support

### ISSUE THREAD

**Issue by Lipata** [IgniteUI/igniteui-cli#578]

**Comment by ViktorSlavov** [comment]
The related PR (#585) removes some unnecessary files, updates the dependencies in the packages.json and changes some settings in the `angular.json` to correspond to the structure of a project generated by `ng new` w/ the latest version (currently, `@angular/cli@9.0.0-next.18`).

**The dependencies in the PR are to beta packages - these should be updated before publish v5.0.0**

**Comment by ViktorSlavov** [comment]
The file structure of the templates is addressed. There is a [separate issue](#590) for the versions update. Closing this.
