### ISSUE TITLE
[Templates] Console errors when starting a project with a bullet graph

### ISSUE THREAD

**Issue by valadzhov** [IgniteUI/igniteui-cli#583]
### Description  
Errors are thrown when you start a project with bullet graph.

- Ignite UI CLI version: 5.0
- Framework: Angular
- Project type: igx-ts

### Steps to reproduce  

1. Add a bullet graph to your project using `ng g @igniteui/angular-schematics:c bullet-graph newBulletGraph`
2. Run the project.

### Result  
An error is shown in the window:
./src/app/app.module.ts
Module not found: Error: Can't resolve 'igniteui-angular-gauges/ES5/igx-bullet-graph-module' in 'D:\test2AngularCLI\my-App\myApp2\src\app'

Additionally there are console errors as well:
 core.js:6014 ERROR Error: Uncaught (in promise): Error: Cannot match any routes. URL Segment: 'newbulletgraph'
Error: Cannot match any routes. URL Segment: 'newbulletgraph'
    at ApplyRedirects.noMatchError (router.js:4295)
    at CatchSubscriber.selector (router.js:4259)
    at CatchSubscriber.error (catchError.js:29)
    at MapSubscriber._error (Subscriber.js:75)
    at MapSubscriber.error (Subscriber.js:55)
    at MapSubscriber._error (Subscriber.js:75)
    at MapSubscriber.error (Subscriber.js:55)
    at MapSubscriber._error (Subscriber.js:75)
    at MapSubscriber.error (Subscriber.js:55)
    at TapSubscriber._error (tap.js:56)
    at resolvePromise (zone-evergreen.js:797)
    at resolvePromise (zone-evergreen.js:754)
    at zone-evergreen.js:858
    at ZoneDelegate.invokeTask (zone-evergreen.js:391)
    at Object.onInvokeTask (core.js:39680)
    at ZoneDelegate.invokeTask (zone-evergreen.js:390)
    at Zone.runTask (zone-evergreen.js:168)

client:150 [WDS] Errors while compiling. Reload prevented.
errors @ client:150
(anonymous) @ socket.js:47
sock.onmessage @ SockJSClient.js:63
EventTarget.dispatchEvent @ sockjs.js:170
(anonymous) @ sockjs.js:887
SockJS._transportMessage @ sockjs.js:885
EventEmitter.emit @ sockjs.js:86
WebSocketTransport.ws.onmessage @ sockjs.js:2961
wrapFn @ zone-evergreen.js:1191
invokeTask @ zone-evergreen.js:391
runTask @ zone-evergreen.js:168
invokeTask @ zone-evergreen.js:465
invokeTask @ zone-evergreen.js:1603
globalZoneAwareCallback @ zone-evergreen.js:1629
client:159 ./src/app/app.module.ts
Module not found: Error: Can't resolve 'igniteui-angular-gauges/ES5/igx-bullet-graph-module' in 'D:\test2AngularCLI\my-App\myApp2\src\app'
errors @ client:159
(anonymous) @ socket.js:47
sock.onmessage @ SockJSClient.js:63
EventTarget.dispatchEvent @ sockjs.js:170
(anonymous) @ sockjs.js:887
SockJS._transportMessage @ sockjs.js:885
EventEmitter.emit @ sockjs.js:86
WebSocketTransport.ws.onmessage @ sockjs.js:2961
wrapFn @ zone-evergreen.js:1191
invokeTask @ zone-evergreen.js:391
runTask @ zone-evergreen.js:168
invokeTask @ zone-evergreen.js:465
invokeTask @ zone-evergreen.js:1603
globalZoneAwareCallback @ zone-evergreen.js:1629
client:159 ./src/app/newbulletgraph/newbulletgraph.component.ts
Module not found: Error: Can't resolve 'igniteui-angular-gauges/ES5/igx-linear-graph-range-component' in 'D:\test2AngularCLI\my-App\myApp2\src\app\newbulletgraph'

### Expected result  
There shouldn't be any errors and the bullet graph project should start.

**Comment by ViktorSlavov** [comment]
This is fixed by #633
