### ISSUE TITLE
Step by step entry points

### ISSUE THREAD

**Issue by damyanpetev** [IgniteUI/igniteui-cli#63]
Besides the `igniteui` command without arguments, the same should be possible via:
- `igniteui new`: Also starts the guide from project creation
- `igniteui add`: Starts directly at the `Add component/template` step

Question: Should the add version also loop like it would after creating project to allow adding multiple views?

**Comment by kdinev** [comment]
@damyanpetev Answer: No. Single view is all that is required.

**Comment by SlavUI** [comment]
@bazal4o moving the task to Sprint 3

**Comment by IvayloG** [comment]
@SlavUI  After a discussion with @kdinev , finally add will loop like it would after creating project. This gives the option to add additional components afterwards.
