### ISSUE TITLE
Creating a new project using `ig new <proj name>` creates a jQuery instead of Angular project 

### ISSUE THREAD

**Issue by IvayloG** [IgniteUI/igniteui-cli#670]
### Description  
Creating a new project using `ig new <proj name>` creates a jQuery project instead of Angular one. 
This behavior differs from `ig new`, where an angular project is created if the <proj name> variable is omitted.

- Ignite UI CLI version: 5.0.0.rc1
- Framework: Angular|jQuery
- Project type: igx-ts

**Comment by Lipata** [comment]
This change will be done in some future major release, both with #579

**Comment by Lipata** [comment]
Now both `ig new <proj name>` and `ig new` default to jQuery project, because for angular the schematics is the main option.
