### ISSUE TITLE
Errors when ig adding a financial chart to a running project

### ISSUE THREAD

**Issue by valadzhov** [IgniteUI/igniteui-cli#678]
### Description  
Adding a financial chart component while the project is running results in a JIT error.

- Ignite UI CLI version: 5.0.0-rc.1
- Framework: Angular
- Project type: igx-ts

### Steps to reproduce  

1. Create a new project with `ng new newAngularProject --collection="@igniteui/angular-schematics" --template=side-nav`
2. Start the project with `ng serve --open`
3. Open another console and ig add a financial chart component: `ig add financial-chart newFinancialChart` (or `ig add awesome-grid newAwesomeGrid`).
4. Examine the console browser's console.

### Result  
There's a JIT error:
core.js:610 Uncaught Error: Angular JIT compilation failed: '@angular/compiler' not loaded!
  - JIT compilation is discouraged for production use-cases! Consider AOT mode instead.
  - Did you bootstrap using '@angular/platform-browser-dynamic' or '@angular/platform-server'?
  - Alternatively provide the compiler with 'import "@angular/compiler";' before bootstrapping.

### Expected result  
There shouldn't be any errors and the project should start normally.

**Comment by dafo** [comment]
This issue is resolved in latest version.
