### ISSUE TITLE
Add a command to list available templates

### ISSUE THREAD

**Issue by damyanpetev** [IgniteUI/igniteui-cli#68]
Since the number of templates has grow quite a bit, it won't be reasonable to list them in readme/docs.
It'll be better if there's a command that can list all available templates, filtered by framework [and project].

**Comment by wnvko** [comment]
After internal discussion the command should work in this way:
- if one is not in a project command without parameters should list all available templates by product group;
- if one is not in a project command with framework and type specified should list all templates for this specific framework/type by product group;
- if one is in a project command should list all templates by product group, related to the framework/type the project was generated for.
