### ISSUE TITLE
Update references to Angular 9.1.x and IgniteUI products

### ISSUE THREAD

**Issue by Lipata** [IgniteUI/igniteui-cli#709]
### Description  
Update references to:
 - Angular 9.1.x
 - [igniteui-angular](https://github.com/IgniteUI/igniteui-angular/releases) 9.1.x
 - [igniteui-angular-charts](https://www.npmjs.com/package/igniteui-angular-charts) 9.1.x
 - [igniteui-angular-wrappers](https://github.com/IgniteUI/igniteui-angular-wrappers/releases) 9.1.x
 - [ignite-ui](https://github.com/IgniteUI/ignite-ui/releases) 20.1

> Note: [this](https://github.com/IgniteUI/igniteui-angular/pull/7121/files) jszip fix in igniteui-angular

**Comment by ViktorSlavov** [comment]
Closed with #714
