### ISSUE TITLE
Fintech Grid template expression changed errors 

### ISSUE THREAD

**Issue by damyanpetev** [IgniteUI/igniteui-cli#717]
### Description  
Describe the issue.

- Ignite UI CLI version: 5.0.x
- Framework: Angular
- Project type: igx-ts

### Steps to reproduce  

1. Create a new project
2. Add the Fintech Grid scenario
3. Run the app and observe the console

### Result  
The two sliders bound to the records and frequency cause:
```
Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: '1000'. Current value: '0'
```

### Expected result  
There should be no error

**Comment by ViktorSlavov** [comment]
Seems to be caused by https://github.com/IgniteUI/igniteui-angular/issues/7336

**Comment by damyanpetev** [comment]
Okay, so the issue is with the slider itself, and as far as I can tell there's no meaningful configuration that can resolve this (short of altering the scenario to not use the slider) and it will be fine once the product is updated.
