### ISSUE TITLE
Make update command prompts more meaningful

### ISSUE THREAD

**Issue by ViktorSlavov** [IgniteUI/igniteui-cli#737]
### Description  
When calling the new `update-packages` command, users get no indication at the beginning of the packages installation. If running the command /w credentials already in place in `.npmrc`, it looks like the console froze and users might cancel the process.

### Additional Info
The package install from the command can be `--quiet` as well (no need to log the ton of packages/warnings)

**Comment by damyanpetev** [comment]
While at it, the command should also handle the possible failure of the install process :)
