### ISSUE TITLE
Creating a new project with licensed packages hangs at user name entry

### ISSUE THREAD

**Issue by wnvko** [IgniteUI/igniteui-cli#748]
### Description  
I am creating a new project either with `ig` command or with `ng new --collection="@igniteui/angular-schematics"`. When I am asked should I upgrade to licensed feed I answer yes. Then it asks me for my user name. After I enter my user name the process hangs forever.

- Ignite UI CLI version: 5.1.0-beta.2
- Framework: Angular
- Project type: igx-ts

### Steps to reproduce  

1. Create a new project with `ig` or `ng + schematics`.
2. When asked `Would you like to upgrade to the licensed feed now?` choose `yes`.
3. Enter your user name when asked.

### Result  
After user name is added nothing happens. The console just hangs forever.

### Expected result  
I should be asked for my password and licensed packages should be installed

### Note
After entering your user name if you click `enter` it again ask you for user name and process finishes correctly.

**Comment by ViktorSlavov** [comment]
Reproducible w/
`node -v`: `v12.16.1`
`npm -v`: `6.13.4`

**Comment by damyanpetev** [comment]
Not so much hangs, but doesn't read the first input correctly I think.
Seems to do with our Step by Step and Inquirer - if I trigger the login process through a command that doesn't prompt (e.g. `ig build/start`) the login works as expected, but if I trigger it though `ig add` and just straight to run it will repro this issue.

So something to do with the state of the `process.stdin` stream after prompt is done.

**Comment by ViktorSlavov** [comment]
This is also reproducible w/ jQuery project & `igniteui-cli@~3.0.0` w/ the stated node & npm versions:
`node -v`: `v12.16.1`
`npm -v`: `6.13.4`
