### ISSUE TITLE
Adding a template with the name of an existing one is overwriting the earlier

### ISSUE THREAD

**Issue by dafo** [IgniteUI/igniteui-cli#76]
**Steps to reproduce:**
1. Create a new project 
2. Add a template 
`add combo myCombo`
3. Add another template using the same command and name

**Actual result:**
The previously created template is replaced by the second template with the same name

**Expected result:**
We should show a message to the user that a template with the same name already exists 
**or**
We should add the second template with incremented name - for example, "myCombo1".

**Comment by SlavUI** [comment]
@damyanpetev hi guys is suggest to add a message the a template with the same name exists and if the user want to overwrite it :)

**Comment by damyanpetev** [comment]
@SlavUI I'd rather we just show a message as expected from above or in the case of step by step guide we can offer the user to provide a different name.

The addition of a view also involves changes to the project config/files and further user changes in those (in addition to the template) are not feasibly traceable. As those have the potential to break the existing project, better to avoid replacing any files if we can.
PS: Changes during add fail gracefully (for the most part) so the new view might not show up, but it shouldn't break anything else.

**Comment by SlavUI** [comment]
@damyanpetev I would like to have this as simple as possible so that users do not get confused and also for us not to change to much code to do the change.
