### ISSUE TITLE
Improve the data visualisation scenarios in the CLI

### ISSUE THREAD

**Issue by StefanIvanov** [IgniteUI/igniteui-cli#764]
### Description  
Enhance the data visualization scenarios in the CLI by adding more scenarios for components such as pie chart, doughnut chart, funnel chart, treemap, and (geo) map as well as splitting the generic category chart into more direct to access scenarios that can be found below. I propose the following structure of the CLI:
-> Charts
  - [x] Financial Chart (_only this one currently exists_)
  - [ ] Bars & Columns
    - [ ] Column
   - [ ] Stacked Column
   - [ ] Stacked 100 Column
   - [ ] Waterfall
   - [ ] Win-Loss
- [ ] Lines
  - [ ] Line
  - [ ] Spline
  - [ ] Sparkline
- [ ] Area
  - [ ] Area
  - [ ] Range Area
  - [ ]  Polar Area
- [ ] Scatter
   - [ ] Point
   - [ ] Bubble
- [ ] Pie Chart
- [ ] Doughnut Chart
- [ ] Funnel Chart
- [ ] Treemap
- [ ] Maps
  - [ ] Map #707 
  - [ ] Density Map
  - [ ] Heat Map
  - [ ] Shape Map

### Attachments  
![charts](https://user-images.githubusercontent.com/1702064/84269596-1824c980-ab32-11ea-9c42-d361d43f4161.png)

**Comment by damyanpetev** [comment]
@StefanIvanov For now we've scheduled adding a map template to components. My concern is still with the structure for the "Charts" - currently both our sites and the CLI structure is based around the actual components (as they exist in code) and we currently have only one level of grouping above them.

That's fine with specialized ones (Pie, Funnel, etc), but with Category and Data Charts there's an overlap that I agree can be confusing - they both have columns, lines, area and points. However, the rest - stacked, scatter and more complex series belong to the Data Chart (not Category as in the image). And the Sparkline is its own thing completely.

What I'm saying is we might need to look at the structure in more detail, if we diverge from the "Group > Component > Sample" levels we have right now in the CLI we might need to do some refactoring and will loose consistency with the main site.

PS: The plot thickens 🙃 Just went to the docs, apparently the Pie and Doughnut have migrated under "Charts > Data Chart > Types" for some reason (not so on main product page). That makes them less discoverable IMHO, and yes I can see how the same argument can be applied to bar/columns and so on.
