### ISSUE TITLE
Ignite UI for Angular startup project template

### ISSUE THREAD

**Issue by kdinev** [IgniteUI/igniteui-cli#87]
The developer should be provided with Ignite UI for Angular as an option after they choose the Angular framework for their repository.

The Ignite UI for Angular should provide the developer with a choice for projects and views specific to Ignite UI for Angular.

**Comment by damyanpetev** [comment]
@kdinev @SlavUI - some details to iron out.
Naming:
- Ignite UI Angular wrappers project name? (currently just "Angular")
- New project name should be "Ignite UI for Angular" right?

Also the command parameter you'd provide when you create such project:
`igniteui new ProjName --framework=angular --type=<?>`

Also we currently have just the basic grid template, you can add other template/view ideas :)

**Comment by kdinev** [comment]
The new project should be `Ignite UI for Angular` and it should come first in the angular selection. The other project should be `Ignite UI Angular Wrappers`. 

`--type=igx-ts` sound good to me.
