### ISSUE TITLE
Errors when starting Angular Wrappers project

### ISSUE THREAD

**Issue by valadzhov** [IgniteUI/igniteui-cli#953]
### Description  
There are errors when creating an Angular Wrappers project.

- Ignite UI CLI version: 9.0.0-rc.3
- Framework: Angular Wrappers

### Steps to reproduce  

1. Create a project with any component.
2. Run the project.

### Result  
There are errors installing the following packages:
![image](https://user-images.githubusercontent.com/9549439/142876980-8090e194-fab5-43fd-83a1-a8b946da8c7d.png)

### Expected result  
The packages should be installed and the project should start without any errors.

**Comment by IvayloG** [comment]
I am closing this as Not Reproducible.
The errors were thrown under an environment having trouble authenticating the user when accessing the licensed package  at https://packages.infragistics.com/npm/js-licensed/
