### ISSUE TITLE
Add more views and scenarios to Web components project

### ISSUE THREAD

**Issue by dafo** [IgniteUI/igniteui-cli#956]
### Description  
More DataGrid/Gauges/Charts views should be added. We can use the existing views in Ignite UI for Angular project.
We should add some complex scenarios.

- Framework: Web Components

### Expected result  
**Grid templates:**

- [x] Grid summaries -> [Sample](https://staging.infragistics.com/products/ignite-ui-web-components/web-components/components/grids/data-grid-column-summaries)
- [x] Grid editing -> [Sample](https://staging.infragistics.com/products/ignite-ui-web-components/web-components/components/grids/data-grid-cell-editing)

**Gauges:**

- [x] Linear gauge -> [Sample](https://staging.infragistics.com/products/ignite-ui-web-components/web-components/components/linear-gauge)
- [x] Radial gauge -> [Sample](https://staging.infragistics.com/products/ignite-ui-web-components/web-components/components/radial-gauge)

**Charts:**

- [x] Financial chart -> [Sample](https://staging.infragistics.com/products/ignite-ui-web-components/web-components/components/charts/types/stock-chart)

**Scenarios:**

- [x] Form view -> [Sample](https://staging.infragistics.com/products/ignite-ui-web-components/web-components/components/inputs/form)

**Comment by dafo** [comment]
The new views are added to [this branch](https://github.com/IgniteUI/igniteui-cli/pull/954/)

**Comment by IvayloG** [comment]
Just a several points here,
1. in a generated project the test comand fails with:
❌ HomeComponent > <my-element> is an instance of MyElement
AssertionError: expected <lit-home></lit-home> to be an instance of HomeComponent
at o.<anonymous> (dist\src\app\home\home.component.test.js:6:31)

2. eslint errors  in a generated project, for example
![image](https://user-images.githubusercontent.com/4296944/144593110-c032fe97-1c24-4d79-abea-448bca1d2fd0.png)

3. Wide/grid sample could benefit fom some right padding like padding-right: 20px; 
...
        margin: 0px;
        padding-left: 275px;
        **padding-right: 20px;**
        width: calc(100% - 275px);.
      }
  ....
