### ISSUE TITLE
Exception is thrown when creating Ignite UI for Angular wrappers project

### ISSUE THREAD

**Issue by dafo** [IgniteUI/igniteui-cli#993]
### Description  
An unhandled exception occurred: Cannot find module '@angular-devkit/build-angular/package.json' is thrown when creating a new Angular Wrappers project.

- Ignite UI CLI version: 9.x.x
- Framework: Angular
- Project type: ig-ts

### Steps to reproduce  

1. Run `ig`
2. Create a new Angular Wrappers project (no matter if empty or not)

### Result  
An unhandled exception occurred: Cannot find module '@angular-devkit/build-angular/package.json'

### Expected result  
Project is generated correctly

### Attachments  
![wrappers1](https://user-images.githubusercontent.com/2778393/151522971-f8aacb4c-8efa-44cf-aa71-b3c7f9fc01ba.png)

**Comment by dafo** [comment]
This is still reproduced in version 11.1.0

**Comment by IvayloG** [comment]
Still reproducible 
![image](https://github.com/IgniteUI/igniteui-cli/assets/4296944/f986f683-4ea2-4d3b-a292-b9b189d05b4e)

**Comment by Lipata** [comment]
https://github.com/IgniteUI/igniteui-angular-wrappers/releases/tag/16.0.0 is released and now this issue can be checked and resolved.
