### ISSUE TITLE
Imports in Web components projects should be added with .js extension

### ISSUE THREAD

**Issue by dafo** [IgniteUI/igniteui-cli#997]
### Description  
Currently imports are missing file extension, resulting in lint errors. TypeScriptFileUpdate.ts should be updated to generate the imports inside app-routing.ts with .js extensions

- Ignite UI CLI version: 9.x.x
- Framework: Web Components
- Project type: igc-ts

### Attachments  
![extension](https://user-images.githubusercontent.com/2778393/152558709-22e970e1-6db6-4e68-a7f8-fae82aff966a.png)

**Comment by Lipata** [comment]
This is already done, even now after https://github.com/IgniteUI/igniteui-cli/pull/1104 they will be with the proper .ts extension.
